In [9]:
import pandas as pd
orders = pd.read_csv("../data/raw/archive/olist_orders_dataset.csv")
customers = pd.read_csv("../data/raw/archive/olist_customers_dataset.csv")
products = pd.read_csv("../data/raw/archive/olist_products_dataset.csv")
payments = pd.read_csv("../data/raw/archive/olist_order_payments_dataset.csv")

In [10]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [11]:
%%sql
SELECT p.payment_value, o.customer_id
FROM payments p
JOIN orders o
ON p.order_id = o.order_id
ORDER BY p.payment_value DESC
LIMIT 10;

   payment_value                       customer_id
0       13664.08  1617b1357756262bfa56ab541c47bc16
1        7274.88  ec5b2ba62e574342386871631fafd3fc
2        6929.31  c6e2731c5b391845f6800c97401a43a9
3        6922.21  f48d464a0baaea338cb25f816991ab1f
4        6726.66  3fd6777bbce08a352fddd04e4a7cc8f6
5        6081.54  05455dfa7cd02f13d132aa7a6a9729c6
6        4950.34  df55c14d1476a9a3467f131269c2477f
7        4809.44  e0a2412720e9ea4f26c1ac985f6a7358
8        4764.34  24bbf5fd2f2e1b359ee7de94defc4a15
9        4681.78  3d979689f636322c62418b6346b1c6d2